//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Librarian
    {
        public Librarian()
        {
            this.LendBook = new HashSet<LendBook>();
            this.ReturnBook = new HashSet<ReturnBook>();
        }
    
        public System.Guid IdLibrarian { get; set; }
        public Nullable<int> IdLibrarianRFID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<LendBook> LendBook { get; set; }
        public virtual ICollection<ReturnBook> ReturnBook { get; set; }
    }
}
