//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderCard
    {
        public ReaderCard()
        {
            this.LendBook = new HashSet<LendBook>();
            this.RequestList = new HashSet<RequestList>();
            this.ReturnBook = new HashSet<ReturnBook>();
        }
    
        public Nullable<int> IdReaderCardRFID { get; set; }
        public System.Guid IdReaderCard { get; set; }
        public System.Guid IdReader { get; set; }
        public string InfoBook { get; set; }
        public string InfoDebt { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual ICollection<LendBook> LendBook { get; set; }
        public virtual Reader Reader { get; set; }
        public virtual ICollection<RequestList> RequestList { get; set; }
        public virtual ICollection<ReturnBook> ReturnBook { get; set; }
    }
}
