//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VKR2
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestList
    {
        public int IdRequestList { get; set; }
        public int IdReaderCardRFID { get; set; }
        public int IdRFIDbook { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.Guid> IdReaderCard { get; set; }
        public Nullable<System.Guid> IdBook { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ReaderCard ReaderCard { get; set; }
    }
}
